apiVersion: v2
name: msa-platform
description: index + market + post
type: application
version: 0.1.0 # chart의 버전
appVersion: "1.0.0" # app 버전

# 의존하는 dependency chart 목록
dependencies:
  - name: index-app
    version: "0.1.0"
    # "file://하위 xhart 의 경로를 작성"
    repository: "file://charts/index"
    condition: index-app.enabled

  - name: market-app
    version: "0.1.0"
    repository: "file://charts/market"
    condition: market-app.enabled

  - name: post-app
    version: "0.1.0"
    repository: "file://charts/post"
    condition: post-app.enabled